### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Coolcat5689** [smaugfm/simple-telegram-forwarder#3]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x61a2b4]

goroutine 1 [running]:
main.(*Config).authorize(0x400012c150)
        simple-telegram-forwarder/auth.go:61 +0x594
main.main()
        simple-telegram-forwarder/main.go:13 +0x30

**Comment by smaugfm** [comment]
@Coolcat5689 please follow README and report if the issues persists
