### ISSUE TITLE
Multiple sources and destinations

### ISSUE THREAD

**Issue by ollegsey** [smaugfm/simple-telegram-forwarder#5]
Sometimes it is required to parse multiple sources and forward messages from them to the one common destination

Sometimes it is needed to forward messages from one sources but to different destinations

It would be great to have an opportunity to make an array of sources and destinations to choose the amount of chat ID's

**Comment by smaugfm** [comment]
Implemented many-to-many forwarding: message received from any of the sources in forwarded/copied to the set of defined destinations. #7
